email:
  send_host: smtp.qq.com
  send_port: 465
  recv_host: imap.qq.com
  recv_port: 993
  user: 2799591178@qq.com
  password: "kenmohcdqtiydgac"
  default_from_email: 话费预警小帮手
  use_ssl: true
  use_tls: true
system:
  host: 127.0.0.1
  port: 8080
  env: debug
jwt:
  secret_key: xx
  expire_time: 48
  issuer: "xx"
mysql:
  host: 127.0.0.1
  port: 3306
  db: base_db
  user: root
  password: "123456"
  log_level: dev
  config: "?charset=utf8&parseTime=true&loc=Local"
redis:
  host: 127.0.0.1
  port: 6379
  password:
  pool_size: 100
expire:
  code_s: 600
  login_h: 48